const industries = [
    'Information Technology',
    'Finance',
    'Healthcare',
    'Education',
    'Manufacturing',
    'Retail',
    'Real Estate',
    'Telecommunications',
    'Hospitality',
    'Transportation',
    'Energy',
    'Media and Entertainment',
    'Consulting',
    'Agriculture',
    'Automotive',
    'Fashion',
    'E-commerce',
    'Biotechnology',
    'Pharmaceuticals',
    'Construction',
    'Nonprofit',
    'Government',
    'Legal',
    'Sports and Recreation',
    'Travel and Tourism',
    'Environmental',
    'Marketing and Advertising',
    'Human Resources',
    'Food and Beverage',
    'Insurance',
    'Technology',
    'Art and Design',
    'Aerospace',
    'Fitness',
    'Gaming',
    'Security',
    'Social Services',
    'Science',
    'Research',
    'Beauty and Cosmetics',
    'Telecommunications',
    'Utilities',
    'Event Planning',
    'Public Relations',
    'Architecture',
    'Logistics',
    'Culinary',
    'Pharmaceuticals',
    'Renewable Energy',
    'Veterinary',
    'Textile',
    'Waste Management',
    'Forestry',
    'Printing',
    'Chemical',
    'Maritime',
    'Mining',
    'Space Exploration',
    'Nanotechnology',
    'Robotics',
    'Automated Systems',
    'Artificial Intelligence',
    'Blockchain',
    'Virtual Reality',
    'Augmented Reality',
    'Clean Energy',
    'Sustainable Agriculture',
    'Water Treatment',
    'Biometrics',
    'Cybersecurity',
    'Data Science',
    'Genetics',
    'Neuroscience',
    'Renewable Energy',
    'Space Tourism',
    '3D Printing',
    'Cryptocurrency',
    'Quantum Computing'
    // Add more industry types as needed
  ];

  export default industries;